### ISSUE TITLE
synchashes could not continue after first fail

### ISSUE THREAD

**Issue by danixeee** [openlawlibrary/OLAAF-Transient#22] opened 2020-04-16 19:18 UTC
`synchashes` command could not continue to insert the data if it failed earlier. It tries to insert `Hash` object without `Path` reference to the database.

Fails at line `Hash.objects.bulk_create(hashes_by_paths_and_types.values())`.

**Comment by renatav** [comment] 2020-05-15 16:36
It appears that this was caused by two synchashes instances running at the same time. synchashes is successfully completed in cases when paths exist and commits don't. I think that we can close this issue

**Closed by renatav** 2020-05-15 16:36 UTC
Labels: bug
